
  
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-test-app
  name: flask-test-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
  selector:
    matchLabels:
      app: flask-test-app
  

---
                        
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-test-app
  name: flask-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - image: docker.io/camchi/hello-flask
          name: flask-test-app
          ports:
            - name: http
              containerPort: 8080
      imagePullPolicy: IfNotPresent
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flask-test-app
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: flask-test-app
              servicePort: http
