apiVersion: v1 
kind: Service 
metadata: 
  name: flask-service 
  labels: 
    app: flask-app
spec: 
  type: LoadBalancer 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 5000
  selector: 
    app: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ${{ secrets.DOCKER_USERNAME }}/hello-flask
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: ingress-flask
 # annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
 #   http:
 #     paths:
 #   - path: /hello 
  #    pathType: 
 #     Prefix backend:
      # Default Path(/)
    #  backend:
      #  serviceName: {{ template "fullname" $ }}-srv
     #   servicePort: 80

