
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: docker.io/pkraja/flask-kubernetes
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP
  selector:
      app: flask-app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    http:
      paths:
      # Default Path(/)
      backend:
        serviceName: {{ template "fullname" $ }}-srv
        servicePort: http
